# Generated by Django 3.1 on 2020-12-27 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20201227_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='currentWinner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
